# Site wide configuration

title: Naiti S. Bhatt         
locale: en_US
url: https://naitisbhatt.github.io
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Naiti S. Bhatt
  avatar: bio.jpg
  position: Lab Manager + Research Associate
  school: New York University
  place: New York City, New York, US
  bio: "Oscillating between amazement with computational cognitive science and adoration for coffee extraction."
  email: naitibhatt@gmail.com
  disqus-shortname:

  twitter: naitisb #username
  facebook: #username
  google:
    plus: 
    analytics: UA-134194584-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  googlescholar: "https://scholar.google.com/citations?user=C0-z5VcAAAAJ&hl=en&oi=ao"
  github: naitisb
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: naiti #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  scholar: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
